# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
arr = np.random.randint(1,20,size=(3,3))
print(arr)

[[ 9 16  2]
 [ 6 19 12]
 [ 5  5 16]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
x=np.zeros((5,5))
n=0
for i in range(0,5):
    for j in range(0,5):
        if (i == (j+1)):
            x[i][j]=n+1
            n=n+1
        else:
            continue
print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
z=np.zeros((8,8))
for i in range(0,8):
    for j in range(0,8):
        if ((i+j)%2 == 0):
            z[i][j]=1
        else:
            z[i][j]=0
print(z)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
x= np.random.randint(10,50,size=(5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[27 26 44 48 40]
 [22 10 20 15 41]
 [26 17 31 33 23]
 [23 15 16 35 13]
 [22 47 38 23 24]]
After normalization:
[[0.44736842 0.42105263 0.89473684 1.         0.78947368]
 [0.31578947 0.         0.26315789 0.13157895 0.81578947]
 [0.42105263 0.18421053 0.55263158 0.60526316 0.34210526]
 [0.34210526 0.13157895 0.15789474 0.65789474 0.07894737]
 [0.31578947 0.97368421 0.73684211 0.34210526 0.36842105]]


# 5.  How to find common values between two arrays?

In [5]:
import numpy as np
array1 = np.array(([1, 2], [3, 1], [2, 4]))
print("Array1: \n",array1)
array2 = np.array(([4, 3],[3, 4], [0, 1]))
print("Array2: \n",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1: 
 [[1 2]
 [3 1]
 [2 4]]
Array2: 
 [[4 3]
 [3 4]
 [0 1]]
Common values between two arrays:
[1 3 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np
today     = np.datetime64('today')
print("Today: ",today)
yesterday = np.datetime64('today') - np.timedelta64(1)
print("Yestraday: ",yesterday)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Tomorrow: ",tomorrow)

Today:  2020-07-26
Yestraday:  2020-07-25
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [7]:
A = np.array([[10,20],[30,40]])
B = np.array([[1,2],[3,4]])

comparison = (A == B)
if (comparison.all()):
    print("Equal")
else:
    print("Not equal")

Not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
def largest(vec,n): 
    max = vec[0] 
    for i in range(1, n): 
        if vec[i] > max: 
            max = vec[i]
            j=i
    vec2[j]=0
    print("Maximum element = ",max)

vec = [10, 32, 45, 90, 9, 5, 66, 1, 63, 15]
print("Original array is : ",vec)
vec2=vec
n = len(vec) 
largest(vec,n)
print("After replacing the maximum element, array is ",vec2)

Original array is :  [10, 32, 45, 90, 9, 5, 66, 1, 63, 15]
Maximum element =  90
After replacing the maximum element, array is  [10, 32, 45, 0, 9, 5, 66, 1, 63, 15]


# 9. How to print all the values of an array?

In [9]:
import numpy as np
array=np.array(([1,2],[3,4],[5,6]))
print(array)

[[1 2]
 [3 4]
 [5 6]]


# 10.Subtract the mean of each row of a matrix

In [11]:
import numpy as np
x = np.array(([10,20],[30,40],[50,60]))
print("Array is: \n",x)
for i in range(0,3):
    y= x[i].mean()
    x[i]=x[i]-a
print("Array after subtracting mean of each row with each element in the row : \n",x)
    

Array is: 
 [[10 20]
 [30 40]
 [50 60]]
Array after subtracting mean of each row with each element in the row : 
 [[ 5 15]
 [25 35]
 [45 55]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [15]:
p = np.ones(10)
c = np.random.randint(0,len(p),20)
p += np.bincount(c, minlength=len(p))
print(p)

[5. 4. 4. 1. 1. 1. 3. 2. 5. 4.]


# 12.How to get the diagonal of a dot product?

In [16]:
A = np.random.randint(0,20,(3,3))
B= np.random.randint(0,20,(3,3))
print("Array 1 : \n",A,"\nArray 2 : \n",B)
np.sum(A * B.T, axis=1)

Array 1 : 
 [[13 19 10]
 [10 13 15]
 [ 0  7  4]] 
Array 2 : 
 [[17 16  7]
 [ 6 14 16]
 [ 8  4 17]]


array([415, 402, 180])

# 13.How to find the most frequent value in an array?

In [18]:
array = np.random.randint(0,10,20)
print ("Array is : \n",arr)
print('Most frequent value is : ', np.bincount(array).argmax())

Array is : 
 [3 4 3 4 5 1 2 1 6 1 3 5 3 1 0 6 6 6 4 8]
Most frequent value is :  1


# 14.How to get the n largest values of an array

In [19]:
x = np.arange(50)
np.random.shuffle(x)
n = 10
print (x[np.argsort(x)[-n:]])

[40 41 42 43 44 45 46 47 48 49]


# 15.How to create a record array from a regular array?

In [22]:
array = np.array([("LetsUpgrade", 10, 15.50),
              ("AI-ML", 20, 30.75)])
rec = np.core.records.fromarrays(arr.T, names='col1, col2, col3')
print("Regular array : \n",array)
print("Record array : \n",rec)

Regular array : 
 [['LetsUpgrade' '10' '15.5']
 ['AI-ML' '20' '30.75']]
Record array : 
 [('Hi', '9.5', '13') ('Hello', '3.6', '32')]
